version: '3'
services:
  conquestdicom:
    image: "rzinkstok/conquest"
    container_name: conquest
    ports:
      - "5678:5678"
    volumes:
      - ./mount:/conquest/mount
#  db:
#    image: postgres
#    restart: always
#    environment:
#      POSTGRES_DB: conquest
#      POSTGRES_USER: conquest
#      POSTGRES_PASSWORD: conquest
    
