version: '3'
services:
  conquestdicom:
    image: "rzinkstok/conquest"
    container_name: conquest
    ports:
      - "${PORT}:${PORT}"
    environment:
      - AETITLE
      - PORT
    volumes:
      - ./mount:/conquest/mount
    depends_on:
      - db
  db:
    image: postgres
    container_name: conquest_db
    restart: always
    environment:
      - POSTGRES_DB=conquest
      - POSTGRES_USER=conquest
      - POSTGRES_PASSWORD=conquest
      - PGDATA=/conquest/dbase
    ports:
      - 5432:5432
    volumes:
      - dbdata:/conquest/dbase

volumes:
  dbdata:
    

